### PR TITLE
Dont show log messages for "WuildNinja --version" call

### PR DESCRIPTION
**Pull request by AlienCowEatCake**
"WuildNinja --version" call should print version only.
Any advanced output will break CMake version detection logic.

### CODE REVIEW

**Review by mapron — CHANGES_REQUESTED** [review]
No need for deferred logs complications.
I'd suggest you to patch ConfiguredApplication constructor, check for version in argv and disable logging in the config,

**Comment by AlienCowEatCake** [comment]
> No need for deferred logs complications.
> I'd suggest you to patch ConfiguredApplication constructor, check for version in argv and disable logging in the config,

All logic is now hidden in `ReadFlags`. Currently there are a little more service parameters than just `--version`. Should we be afraid of possible problems in the future if we use the proposed way?

**Comment by mapron** [comment]
You can't call ReadFlags before wuild would process its flags and remove what it recognize. So we kinda can't just rely on ReadFlags for this purpose. 
You can also try such a thing: move cmd parsing outside of ConfiguredApplication; then call ReadFlags, and then construct everything else with parsed config if you really concern we can get any trouble in the future. 
That probably will be the most elegant solution, but I'm feel I'm keen on keeping this as simple as possible.

**Comment by mapron** [comment]
Closing this as no action performed. I will do the changes by myself.

**Pull request closed without merging**
